---

# Tenant variables
params:
  # Tenant parameters
  tenant_name: DevNet01 
  tenant_description: DevNetTest

   # Bridge Domain & Subnet   
  bd_name: DevNet
  bd_subnet_gateway: 10.1.1.1
  bd_subnet_mask: 24

  # Application Profile 
  ap_name: Production
  ap_description: Production Application Profile

  ######### End Point Groups #########
  epglist:
  - name: 'FrontEnd'
    description: "Production FrontEnd Servers" 
  - name: 'Middleware'
    description: "Production Middleware Servers" 
  - name: 'Databases'
    description: "Production Database Servers" 

  ######### Filter & Entry Creation #########

  first_filter_filter: Filter_HTTP
  first_filter_entry: HTTP
  first_filter_ether_name: ip
  first_filter_ip_protocol: tcp
  first_filter_dst_port: 80

  ######### Contract & Subject Creation #########

  first_contract_contract: Contract_HTTPS
  first_contract_description: 'Allow HTTP Traffic'
  first_contract_scope: context
  first_contract_subject: Subj_HTTPS
  first_contract_subject_reverse_filter: yes